# Project: aisd3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = trzy_liczby_w_kolejnosci_rosnacej.o liczby_dwucyfrowe_w_kolejnosci_rosnacej.o
LINKOBJ  = trzy_liczby_w_kolejnosci_rosnacej.o liczby_dwucyfrowe_w_kolejnosci_rosnacej.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AISD3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

trzy_liczby_w_kolejnosci_rosnacej.o: trzy_liczby_w_kolejnosci_rosnacej.cpp
	$(CPP) -c trzy_liczby_w_kolejnosci_rosnacej.cpp -o trzy_liczby_w_kolejnosci_rosnacej.o $(CXXFLAGS)

liczby_dwucyfrowe_w_kolejnosci_rosnacej.o: liczby_dwucyfrowe_w_kolejnosci_rosnacej.cpp
	$(CPP) -c liczby_dwucyfrowe_w_kolejnosci_rosnacej.cpp -o liczby_dwucyfrowe_w_kolejnosci_rosnacej.o $(CXXFLAGS)
